name: Run tests

on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # See https://github.com/satackey/action-docker-layer-caching
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the Docker image
        run: docker build --tag docker-node-puppeteer .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name test-container docker-node-puppeteer

      - name: Run tests
        run: docker exec -it test-container node server.spec.js
